### ISSUE TITLE
Links To Relevant Info

### ISSUE THREAD

**Issue by derek-baker** [arevi/utica-tweets#1]
Is there anything worth linking to for this? (Twitter account, sites, etc)

Just curious what's going on.

**Comment by arevi** [comment]
Hey Derek!

I should probably update the readme to provide a bit more detail.

It's actually the source code for a development club meeting. It's provided here for the attendees to download and review, while we do a live codealong.

The basis is providing a relatively simple API implementation with Express and MongoDB.

Then we'll be building a frontend solution in Angular to render the tweets sent to the server, and submit tweets of your own!

It's really barebones, but provides some insight into modeling data with Angular, component reuse and all the goodness that comes from using frontend frameworks. (headaches left out of course)

Hope all is well with you!
